# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tracking.proto
# Protobuf Python Version: 7.34.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    0,
    '',
    'tracking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etracking.proto\x12\x12jernerics.tracking\"\xd9\x02\n\x08\x45nvelope\x12\x12\n\nstudy_name\x18\x01 \x01(\t\x12\x10\n\x08trial_id\x18\x02 \x01(\x05\x12\x14\n\x0ctimestamp_ns\x18\x03 \x01(\x03\x12\x38\n\nsweep_meta\x18\x04 \x01(\x0b\x32\".jernerics.tracking.SweepMetaEventH\x00\x12/\n\x05param\x18\x05 \x01(\x0b\x32\x1e.jernerics.tracking.ParamEventH\x00\x12\x31\n\x06metric\x18\x06 \x01(\x0b\x32\x1f.jernerics.tracking.MetricEventH\x00\x12\x31\n\x06result\x18\x07 \x01(\x0b\x32\x1f.jernerics.tracking.ResultEventH\x00\x12\x35\n\x08\x61rtifact\x18\x08 \x01(\x0b\x32!.jernerics.tracking.ArtifactEventH\x00\x42\t\n\x07payload\"2\n\x0eSweepMetaEvent\x12\x10\n\x08git_hash\x18\x01 \x01(\t\x12\x0e\n\x06\x63onfig\x18\x02 \x01(\t\"b\n\x05Value\x12\x13\n\tfloat_val\x18\x01 \x01(\x01H\x00\x12\x11\n\x07int_val\x18\x02 \x01(\x03H\x00\x12\x14\n\nstring_val\x18\x03 \x01(\tH\x00\x12\x12\n\x08\x62ool_val\x18\x04 \x01(\x08H\x00\x42\x07\n\x05value\"C\n\nParamEvent\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.jernerics.tracking.Value\"7\n\x0bMetricEvent\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x0c\n\x04step\x18\x03 \x01(\x03\")\n\x0bResultEvent\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"0\n\rArtifactEvent\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x12\n\nlocal_path\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tracking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVELOPE']._serialized_start=39
  _globals['_ENVELOPE']._serialized_end=384
  _globals['_SWEEPMETAEVENT']._serialized_start=386
  _globals['_SWEEPMETAEVENT']._serialized_end=436
  _globals['_VALUE']._serialized_start=438
  _globals['_VALUE']._serialized_end=536
  _globals['_PARAMEVENT']._serialized_start=538
  _globals['_PARAMEVENT']._serialized_end=605
  _globals['_METRICEVENT']._serialized_start=607
  _globals['_METRICEVENT']._serialized_end=662
  _globals['_RESULTEVENT']._serialized_start=664
  _globals['_RESULTEVENT']._serialized_end=705
  _globals['_ARTIFACTEVENT']._serialized_start=707
  _globals['_ARTIFACTEVENT']._serialized_end=755
# @@protoc_insertion_point(module_scope)
