from typing import Protocol

from .models import JobInfo, SweepSpec


class Backend(Protocol):
    def submit_sweep(self, spec: SweepSpec) -> str: ...
    def list_jobs(self, include_completed: bool = False) -> list[JobInfo]: ...
    def cancel(self, job_id: str) -> bool: ...
    def cancel_all(self) -> bool: ...
    def get_status(self, job_id: str) -> str | None: ...
    def wait_for_completion(
        self, job_id: str, poll_interval: float = 30, timeout: float | None = None
    ) -> bool: ...
